steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/fb-studio-video-captioner/cloud-run-source-deploy/no-code-architects-toolkit-fb-studio-727799334232:latest',
    '.'
  ]
options:
  machineType: 'E2_HIGHCPU_8' # Use a faster machine type
images:
- 'us-central1-docker.pkg.dev/fb-studio-video-captioner/cloud-run-source-deploy/no-code-architects-toolkit-fb-studio-727799334232:latest'
timeout: 7200s # Increase timeout to 2 hours
